=== denitsa-r/XML-solutions/07-2014-ex8/mySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="notebook">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="record" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="first_name"/>
              <xs:element ref="father_name"/>
              <xs:element ref="last_name"/>
              <xs:element ref="address"/>
              <xs:element ref="date_of_birth"/>
              <xs:element ref="phones" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="relative"/>
                  <xs:enumeration value="colleague"/>
                  <xs:enumeration value="acquaintance"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="first_name" type="xs:string"/>
  <xs:element name="father_name" type="xs:string"/>
  <xs:element name="last_name" type="xs:string"/>
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="place_of_living" type="xs:string"/>
        <xs:element name="street">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="number" type="xs:integer"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="post_code" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="date_of_birth" type="xs:date"/>
  <xs:element name="phones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="phone" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="type" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="personal"/>
                      <xs:enumeration value="work"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== denitsa-r/XML-solutions/07-2014-ex8/2014-ex.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE notebook [
  <!ELEMENT notebook (record*)>
  <!ELEMENT record (first_name, father_name, last_name, address, date_of_birth?, phones?)>
  <!ELEMENT first_name (#PCDATA)>
  <!ELEMENT father_name (#PCDATA)>
  <!ELEMENT last_name (#PCDATA)>
  <!ELEMENT address (place_of_living, street)>
  <!ELEMENT place_of_living (#PCDATA)>
  <!ELEMENT street (#PCDATA)>
  <!ELEMENT date_of_birth (#PCDATA)>
  <!ELEMENT phones (phone*)>
  <!ELEMENT phone (#PCDATA)>
  <!ATTLIST record type (relative|colleague|acquaintance) #REQUIRED
                    id ID #REQUIRED>
  <!ATTLIST address post_code CDATA #REQUIRED>
  <!ATTLIST street number CDATA #REQUIRED>
  <!ATTLIST phone type (personal|work) #REQUIRED>
  <!ATTLIST notebook xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation CDATA #FIXED "mySchema.xsd">
]>
<notebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mySchema.xsd">
  <record type="relative" id="rec001">
    <first_name>Denitsa</first_name>
    <father_name>Krasimirova</father_name>
    <last_name>Rashkova</last_name>
    <address post_code="4270">
      <place_of_living>Purvomai</place_of_living>
      <street number="11">Dragoyna</street>
    </address>
    <date_of_birth>2003-07-14</date_of_birth>
    <phones>
      <phone type="personal">
        0895475236
      </phone>
    </phones>
  </record>
  <record type="colleague" id="rec002">
    <first_name>Nqkoi</first_name>
    <father_name>Bashta</father_name>
    <last_name>Familiq</last_name>
    <address post_code="1234">
      <place_of_living>Ime</place_of_living>
      <street number="11">Ime</street>
    </address>
    <date_of_birth>2003-07-14</date_of_birth>
    <phones>
      <phone type="work">
        0895475236
      </phone>
    </phones>
  </record>
  <record type="acquaintance" id="rec003">
    <first_name>Nqkoi</first_name>
    <father_name>Bashta</father_name>
    <last_name>Familiq</last_name>
    <address post_code="1234">
      <place_of_living>Ime</place_of_living>
      <street number="11">Ime</street>
    </address>
    <date_of_birth>2003-07-14</date_of_birth>
    <phones>
      <phone type="work">
        0895475236
      </phone>
    </phones>
  </record>
</notebook>
